doctrine:
    dbal:
        connections:
            default:
                driver: pdo_pgsql
                server_version: '11.2'
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    jsonb: jsonb
        types:
            jsonb: App\Doctrine\DBAL\Types\Jsonb
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        CONTAINS: App\Doctrine\ORM\Query\AST\Functions\Contains
