imports:
    - { resource: easy_admin/*.yml }

easy_admin:
    site_name: '🚀 Starfleet'
    design:
        brand_color: '#0C1A31'
        menu:
            - { entity: 'User', label: 'Users', icon: 'users' }
            - { entity: 'Conference', label: 'Conferences', icon: 'calendar' }
            - { entity: 'Participation', label: 'Participations', icon: 'id-badge' }
            - { entity: 'Talk', label: 'Talks', icon: 'commenting' }
            - { entity: 'Tag', label: 'Tags', icon: 'tag' }
        assets:
            css:
                - 'build/css/admin.css'
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'build/js/admin.js'
                - 'bundles/easyadmin/bootstrap-all.js'
        templates:
            layout: 'easy_admin/layout.html.twig'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    list:
        actions:
            - { name: 'show', icon: 'eye' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
