imports:
    - { resource: easy_admin/*.yaml }

easy_admin:
    site_name: '🚀 Starfleet'
    design:
        brand_color: '#0C1A31'
        menu:
            - { entity: 'NextConference', label: 'Next Conferences', icon: 'forward', default: true }
            - { entity: 'PassedConference', label: 'Passed Conferences', icon: 'backward' }
            - { entity: 'ExcludedConference', label: 'Excluded Conferences', icon: 'times' }
            - { entity: 'Participation', label: 'Participations', icon: 'id-badge' }
            - { entity: 'Talk', label: 'Talks', icon: 'file-text-o' }
            - { entity: 'ConferenceFilter', label: 'Ignored Subjects', icon: 'times' }
            - { entity: 'User', label: 'Users', icon: 'users' }
            - { entity: 'Continent', label: 'Continents', icon: 'globe' }
            - { label: 'Fetchers', route: 'fetcher_list', icon: 'bell' }
        assets:
            css:
                - 'build/css/admin.css'
        templates:
            layout: 'easy_admin/layout.html.twig'
    user:
        name_property_path: 'name'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    list:
        actions:
            - { name: 'show', icon: 'eye' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
