framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    http_method_override: false

    session:
        handler_id: null
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    trusted_hosts:
        - '%env(TRUSTED_HOSTS)%'
        - 'localhost'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
