framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    session:
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    trusted_hosts:
        - '%env(TRUSTED_HOSTS)%'
        - 'localhost'
