knpu_oauth2_client:
    clients:
        google_main:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
            access_type: ''
            hosted_domain: ''
            user_fields: {}
