twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/templates': app
        '%kernel.project_dir%/assets/images': images
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
