framework:
    workflows:
        participation_request:
            type: state_machine
            marking_store:
                type: 'method'
                property: 'marking'
            supports:
                - App\Entity\Participation
            initial_marking: pending

            places:
                - pending
                - rejected
                - accepted
                - cancelled

            transitions:
                -   name: !php/const App\Enum\Workflow\Transition\Participation::ACCEPT
                    guard: "is_granted('ROLE_ADMIN')"
                    from: [pending, rejected, cancelled]
                    to: accepted
                    metadata:
                        title: 'Accept'

                -   name: !php/const App\Enum\Workflow\Transition\Participation::REJECT
                    guard: "is_granted('ROLE_ADMIN')"
                    from: [pending, accepted]
                    to: rejected
                    metadata:
                        title: 'Reject'

                -   name: !php/const App\Enum\Workflow\Transition\Participation::CANCEL
                    guard: "is_granted('ROLE_ADMIN')"
                    from: [pending, accepted]
                    to: cancelled
                    metadata:
                        title: 'Cancel'
