framework:
    workflows:
        participation_request:
            type: state_machine
            marking_store:
                type: 'method'
                property: 'marking'
            supports:
                - App\Entity\Participation
            initial_marking: pending

            places:
                - pending
                - rejected
                - accepted
                - cancelled

            transitions:
                -   name: !php/const App\Enum\Workflow\Transition\Participation::ACCEPTED
                    from: [pending, rejected, cancelled]
                    to: accepted
                    metadata:
                        title: 'Accept'

                -   name: !php/const App\Enum\Workflow\Transition\Participation::REJECTED
                    from: [pending, accepted]
                    to: rejected
                    metadata:
                        title: 'Reject'

                -   name: !php/const App\Enum\Workflow\Transition\Participation::CANCELLED
                    from: [pending, accepted]
                    to: cancelled
                    metadata:
                        title: 'Cancel'
