<?php

/*
 * This file is part of the Starfleet Project.
 *
 * (c) Starfleet <msantostefano@jolicode.com>
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */

namespace App\Enum;

use MyCLabs\Enum\Enum;

class TagEnum extends Enum
{
    private const ANDROID = 'Android'; //0
    private const APPLE = 'Apple'; //1
    private const C_PLUSPLUS = 'C++'; //2
    private const CSS = 'CSS'; //3
    private const DART = 'Dart'; //4
    private const DATA = 'Data'; //5
    private const DEVOPS = 'DevOps'; //6
    private const DOTNET = 'Dotnet'; //7
    private const ELIXIR = 'Elixir'; //8
    private const FACEBOOK = 'Facebook'; //9
    private const FLUTTER = 'Flutter'; //10
    private const GENERAL = 'General'; //11
    private const GO = 'Go'; //12
    private const GOOGLE = 'Google'; //13
    private const GRAPHQL = 'GraphQL'; //14
    private const HTML = 'HTML'; //15
    private const IOS = 'iOS'; //16
    private const JAVA = 'Java'; //17
    private const JAVASCRIPT = 'Javascript'; //18
    private const MICROSOFT = 'Microsoft'; //19
    private const NODEJS = 'NodeJS'; //20
    private const PHP = 'PHP'; //21
    private const PYTHON = 'Python'; //22
    private const REACT_NATIVE = 'React Native'; //23
    private const RUBY = 'Ruby'; //24
    private const RUST = 'Rust'; //25
    private const SCALA = 'Scala'; //26
    private const SECURITY = 'Security'; //27
    private const TECH_COMM = 'TechComm'; //28
    private const UX = 'UX'; //29

    public function __construct($value)
    {
        parent::__construct($value);
    }

    public function getValue()
    {
        return parent::getValue(); // TODO: Change the autogenerated stub
    }

    public function setValue($value): void
    {
        $this->value = $value;
    }

    public function getKey()
    {
        return parent::getKey(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    public static function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public static function search($value)
    {
        return parent::search($value); // TODO: Change the autogenerated stub
    }
}
