<?php

/*
 * This file is part of the Starfleet Project.
 *
 * (c) Starfleet <msantostefano@jolicode.com>
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */

namespace App\Enum;

use MyCLabs\Enum\Enum;

class TagEnum extends Enum
{
    private const CSS = 'CSS';
    private const HTML = 'HTML';
    private const JAVASCRIPT = 'Javascript';
    private const RUBY = 'Ruby';
    private const PHP = 'PHP';
    private const GO = 'Go';
    private const ELIXIR = 'Elixir';
    private const NODEJS = 'NodeJS';
    private const C_PLUSPLUS = 'C++';
    private const RUST = 'Rust';
    private const SCALA = 'Scala';
    private const PYTHON = 'Python';
    private const DOTNET = 'Dotnet';
    private const JAVA = 'Java';
    private const DART = 'Dart';
    private const DEVOPS = 'DevOps';
    private const ANDROID = 'Android';
    private const IOS = 'iOS';
    private const REACT_NATIVE = 'React Native';
    private const FLUTTER = 'Flutter';
    private const GRAPHQL = 'GraphQL';
    private const DATA = 'Data';
    private const SECURITY = 'Security';
    private const GENERAL = 'General';
    private const TECH_COMM = 'TechComm';
    private const GOOGLE = 'Google';
    private const APPLE = 'Apple';
    private const FACEBOOK = 'Facebook';
    private const MICROSOFT = 'Microsoft';

    public function __construct($value)
    {
        parent::__construct($value);
    }

    public function getValue()
    {
        return parent::getValue(); // TODO: Change the autogenerated stub
    }

    public function setValue($value): void
    {
        $this->value = $value;
    }

    public function getKey()
    {
        return parent::getKey(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    public static function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public static function search($value)
    {
        return parent::search($value); // TODO: Change the autogenerated stub
    }
}
