version: 2

jobs:
    check-php-cs:
        docker:
            - image: circleci/php:7.3-node-browsers
        steps:
            - checkout
            - run:
                  name: Install PHP CS Fixer
                  command: wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
            - run:
                  name: Check PHP CS
                  command: php php-cs-fixer fix --dry-run --allow-risky yes --diff --config=.php_cs

    check-python-cs:
        docker:
            - image: circleci/python:2.7
        working_directory: ~/project
        steps:
            - checkout
            - run: sudo pip install pycodestyle
            - run:
                  name: Check cs
                  command: pycodestyle fabfile.py --ignore=E501,W605,E722

    check-lint:
        docker:
            - image: circleci/php:7.3-node-browsers
        working_directory: ~/project
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - composer-cache-project-{{ checksum "~/project/composer.lock" }}
                      - composer-cache-
            - run: sudo docker-php-ext-install bcmath pcntl pdo_mysql
            - run:
                  name: Composer install
                  command: composer install --no-scripts
            - run:
                  name: Create .env
                  command: cp .env.dist .env
            - save_cache:
                  key: composer-cache-project-{{ checksum "~/project/composer.lock" }}
                  paths:
                      - ~/.composer
            - run:
                  name: Lint YAML
                  command: php bin/console lint:yaml --parse-tags config/
                  when: always
            - run:
                  name: Lint Twig
                  command: php bin/console lint:twig templates/
                  when: always

    tests:
        machine:
            docker_layer_caching: true
        working_directory: ~/project
        steps:
            - checkout
            - restore_cache:
                keys:
                    - func-cache-{{ checksum "~/project/composer.lock" }}
                    - func-cache-

            - run:
                name: Prepare cache
                command: |
                    set -x
                    mkdir -p ~/.composer
            - run:
                name: Create .env
                command: cp .env.ci.dist .env

            - run:
                name: Install Requirements
                command: |
                    set -x
                    pip install pipenv==11.1.4
                    pipenv install
            - run:
                name: Install and build everything
                command: |
                    set -x
                    pipenv run fab start
                    pipenv run fab webpack
            - run:
                name: Run unit and functional tests
                command: |
                    set -x
                    pipenv run fab tests

            - save_cache:
                key: func-cache-{{ checksum "~/project/composer.lock" }}
                paths:
                    - ~/.composer

workflows:
    version: 2
    check_and_tests:
        jobs:
            - check-php-cs
            - check-python-cs
            - check-lint
            - tests
