version: 2

jobs:
    build:
        machine: true
        working_directory: ~/starfleet
        steps:
            - checkout
            - restore_cache:
                name: Restore Docker cache
                key: docker-images-{{ arch }}-{{ checksum ".circleci/.circle-cache-docker" }}
            - restore_cache:
                name: Restore yarn packages cache
                key: yarn-packages-deps-{{ arch }}-{{ checksum "yarn.lock" }}
            - restore_cache:
                name: Restore composer packages cache
                key: composer-packages-deps-{{ arch }}-{{ checksum "composer.lock" }}
            - run:
                name: Prepare cache
                command: |
                    set -x
                    mkdir -p ~/.composer
                    mkdir -p ~/.cache/yarn
                    mkdir -p ~/.docker-images
                    touch .php_cs.cache
            - restore_cache:
                name: Restore PHP CS Fixer cache
                key: php-cs-fixer-{{ arch }}-{{ checksum ".php_cs.cache" }}
            - run:
                name: pip install
                command: pip install -r requirements.txt
            - run:
                name: Build Infrastructure - Load cache
                command: |
                    set -x
                    fab ci.circle.load_cache
            - run:
                name: Build Infrastructure - Save cache
                command: |
                    set -x
                    fab ci.circle.save_cache
            - save_cache:
                name: Save Docker cache
                key: docker-images-{{ arch }}-{{ checksum ".circleci/.circle-cache-docker" }}
                paths:
                    - ~/.docker-images
            - run:
                name: Install everything
                command: |
                    set -x
                    fab ci.infrastructure.up
                    fab ci.frontend.install
                    fab ci.frontend.webpack_build
            - save_cache:
                name: Save yarn packages cache
                key: yarn-packages-deps-{{ arch }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - save_cache:
                name: Save composer packages cache
                key: composer-packages-deps-{{ arch }}-{{ checksum "composer.lock" }}
                paths:
                    - ~/.composer
            - run:
                name: QA PHPUnit
                command: fab ci.qa.phpunit
            - save_cache:
                name: Save PHP CS Fixer cache
                key: php-cs-fixer-{{ arch }}-{{ checksum ".php_cs.cache" }}
                paths:
                    - ~/.php_cs.cache
            - run:
                name: QA lint
                command: fab ci.qa.check_cs
