version: 2.1

jobs:
    check-php-cs:
        docker:
            - image: circleci/php:8.0-node-browsers
        steps:
            - checkout
            - run:
                  name: Install PHP CS Fixer
                  command: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.0.0/php-cs-fixer.phar -O php-cs-fixer
            - run:
                  name: Check PHP CS
                  command: php php-cs-fixer fix --dry-run --allow-risky yes --diff --config=.php-cs-fixer.php

    check-python-cs:
        docker:
            - image: cimg/python:3.7
        working_directory: ~/project
        steps:
            - checkout
            - run: pip install pycodestyle
            - run:
                  name: Check cs
                  command: pycodestyle --ignore=E501,W605,E722 invoke.py tasks.py

    check-lint:
        docker:
            - image: circleci/php:8.0-node-browsers
        working_directory: ~/project
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - composer-cache-project-{{ checksum "~/project/composer.lock" }}
                      - composer-cache-
            - run: sudo docker-php-ext-install bcmath pcntl pdo_mysql
            - run:
                  name: Composer install
                  command: composer install --no-scripts
            - save_cache:
                  key: composer-cache-project-{{ checksum "~/project/composer.lock" }}
                  paths:
                      - ~/.composer
            - run:
                  name: Lint YAML
                  command: php bin/console lint:yaml --parse-tags config/
                  when: always
            - run:
                  name: Lint Twig
                  command: php bin/console lint:twig templates/
                  when: always
            - run:
                    name: Run PHPStan
                    command: php -d memory_limit=-1 vendor/bin/phpstan analyse

    tests:
        machine:
            docker_layer_caching: true
            image: ubuntu-2004:202107-02
        working_directory: ~/project
        steps:
            - checkout
            - restore_cache:
                keys:
                    - func-cache-{{ checksum "~/project/composer.lock" }}
                    - func-cache-

            - run:
                name: Prepare cache
                command: |
                    set -x
                    mkdir -p ~/.composer
            - run:
                name: Create .env
                command: cp .env.ci.dist .env

            - run:
                name: Install Requirements
                command: |
                    set -e
                    pyenv global 3.9.4
                    pip install --upgrade pip
                    pip install pipenv
                    pipenv install
            - run:
                name: Install and build everything
                command: |
                    set -x
                    pipenv run inv start
                    pipenv run inv webpack
            - run:
                name: Run unit and functional tests
                command: |
                    set -x
                    pipenv run inv tests

            - save_cache:
                key: func-cache-{{ checksum "~/project/composer.lock" }}
                paths:
                    - ~/.composer

workflows:
    version: 2
    check_and_tests:
        jobs:
            - check-php-cs
            - check-python-cs
            - check-lint
            - tests
