[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
      regex = "^http://.*"
      replacement = "https://$1"
      permanent = false
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
       CertFile = "/etc/ssl/certs/cert.pem"
       KeyFile = "/etc/ssl/certs/key.pem"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
