version: '3'

volumes:
    postgres-data: {}

services:
    router:
        build: services/router
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        # # Use network alias if you need to access a container via a specific
        # # host by using the routing from another container
        # networks:
        #     default:
        #         aliases:
        #             - api.app.test
        labels:
            - "traefik.enable=false"

    frontend:
        build: services/frontend
        depends_on:
            - database
        volumes:
            - "../../${PROJECT_DIRECTORY}:/var/www:cached"
        labels:
            - "traefik.port=80"
            - "traefik.frontend.entryPoints=https"
            - "traefik.frontend.rule=Host:${PROJECT_HOSTNAMES}"

    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=starfleet
            - POSTGRES_PASSWORD=starfleet
            - POSTGRES_DB=starfleet
        volumes:
            - "database-data:/var/lib/postgresql/data"
        labels:
            - "traefik.enable=false"
        ports:
            - "5432:5432"
