parameters:
    locale: 'en'
    router.request_context.host: '%env(ROUTER_HOST)%'
    router.request_context.scheme: 'https'
    asset.request_context.secure: true

services:
    _instanceof:
        App\Fetcher\FetcherInterface:
            tags: ['app.fetcher']

    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\DoctrineEventSubscriber:
        arguments:
            $router: '@router'
        tags: ['doctrine.event_subscriber']

    App\SlackNotifier:
        arguments:
            $webHookUrl: '%env(SLACK_WEB_HOOK_URL)%'
            $env: '%env(APP_ENV)%'

    twig.date_extension:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    App\Conferences\ConferencesHarvester:
        arguments:
            $fetchers: !tagged_iterator { tag: 'app.fetcher' }

    App\Security\Authenticator\GitHubAuthenticator:
        arguments:
            $allowedGitHubOrganization: '%env(APP_ALLOWED_GITHUB_ORGANIZATION)%'

    Http\Adapter\Guzzle6\Client:

    Geocoder\Provider\Nominatim\Nominatim:
        arguments:
            $client: '@Http\Adapter\Guzzle6\Client'
            $rootUrl: 'https://nominatim.openstreetmap.org/'
            $userAgent: 'Fetch some geoloc thx OSM'

    Geocoder\StatefulGeocoder:
        arguments:
            $provider: '@Geocoder\Provider\Nominatim\Nominatim'
            $locale: 'en'
    
    App\Controller\Admin\FetcherController:
        arguments:
            - !tagged_locator { tag: 'app.fetcher' }
    
    App\Fetcher\ConfTechFetcher:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Twig\MapboxUrlEncoder:
        arguments:
            $apiToken: '%env(MAPBOX_TOKEN)%'
