parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # @todo: check to use _instanceof for auto-tag FetcherInterface implementations
    App\Fetcher\:
        resource: '../src/Fetcher'
        tags: ['app.fetcher']

    App\EventListener\DoctrineEventSubscriber:
        arguments:
            $router: '@router'
        tags: ['doctrine.event_subscriber']

    App\SlackNotifier:
        arguments:
            $webHookUrl: '%env(SLACK_WEB_HOOK_URL)%'

    App\DataFixtures\ORM\:
        resource: '../src/DataFixtures/ORM'
        tags: [doctrine.fixture.orm]

    twig.date_extension:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    App\Command\FetchConferencesCommand:
        arguments:
            - !tagged app.fetcher
            - '@doctrine'
