easy_admin:
    entities:
        PassedConference:
            class: App\Entity\Conference
            list:
                sort: ['endAt', 'DESC']
                dql_filter: 'entity.endAt < CURRENT_DATE()'
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'startAt', type: 'date' }
                    - { property: 'endAt', type: 'date' }
                    - { property: 'tags', type: 'array' }
        Conference:
            class: App\Entity\Conference
            disabled_actions: ['show']
            list:
                sort: ['startAt', 'ASC']
                dql_filter: 'entity.startAt >= CURRENT_DATE()'
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'startAt', type: 'date' }
                    - { property: 'cfpUrl', type: 'url', template: 'easy_admin/Conference/cfpUrl.html.twig' }
                    - { property: 'cfpEndAt', type: 'date' }
                    - { property: 'tags', type: 'array' }
            form:
                fields:
                    - { type: 'group', columns: 4, icon: 'pencil', label: 'Conference' }
                    - { property: 'name', type: 'text' }
                    - { property: 'location', type: 'text' }
                    - { property: 'startAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'endAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'siteUrl', type: 'url' }
                    - { type: 'group', columns: 4, icon: 'bullhorn', label: 'CFP' }
                    - { property: 'cfpUrl', type: 'url' }
                    - { property: 'cfpEndAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { type: 'group', columns: 4, icon: 'cubes', label: 'Metadata' }
                    - { property: 'tags' }
                    - { property: 'articleUrl', type: 'url' }
