easy_admin:
    entities:
        PassedConference:
            class: App\Entity\Conference
            controller: App\Controller\Admin\ConferenceController
            disabled_actions: ['edit', 'delete', 'new']
            list:
                title: 'Passed Conferences'
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'excludeConference', label: 'Exclude', icon: 'times' }
                sort: ['endAt', 'DESC']
                dql_filter: 'entity.endAt < CURRENT_DATE() AND entity.excluded = false'
                fields: &conferenceListFields
                    - { property: 'name', type: 'text' }
                    - { property: 'city', type: 'text' }
                    - { property: 'country', type: 'country', template: 'easy_admin/Conference/country.html.twig'}
                    - { property: 'startAt', type: 'date' }
                    - { property: 'cfpUrl', type: 'url', template: 'easy_admin/Conference/cfpUrl.html.twig' }
                    - { property: 'cfpEndAt', type: 'date' }
                    - { property: 'source', type: 'text' }
                    - { property: 'tags', type: 'array' }
            show:
                fields: &conferenceShowFields
                    1: { property: name, type: text }
                    2: { property: city, type: text }
                    3: { property: country, type: country }
                    4: { property: source, type: text }
                    5: { property: description, type: text}
                    6: { property: startAt, type: date }
                    7: { property: endAt, type: date }
                    8: { property: cfpUrl, type: url }
                    9: { property: cfpEndAt, type: date }
                    10: { property: siteUrl, type: url }
                    11: { property: articleUrl, type: url }
                    12: { property: submits, label: 'Submissions', type: embedded_list, css_class: "d-block mx-auto" }
                    13: { property: participations, type: embedded_list, css_class: "d-block mx-auto" }
        NextConference:
            class: App\Entity\Conference
            controller: App\Controller\Admin\ConferenceController
            disabled_actions: ['delete']
            list:
                title: 'Next Conferences'
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'excludeConference', label: 'Exclude', icon: 'times' }
                sort: ['startAt', 'ASC']
                dql_filter: 'entity.endAt >= CURRENT_DATE() AND entity.excluded = false'
                fields:
                    <<: *conferenceListFields
            form:
                fields: &conferencesEditFields
                    - { type: 'group', columns: 4, icon: 'pencil', label: 'Conference' }
                    - { property: 'name', type: 'text' }
                    - { property: 'city', type: 'text' }
                    - { property: 'country', type: 'country' }
                    - { property: 'online', type: 'checkbox' }
                    - { property: 'startAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'endAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'siteUrl', type: 'url' }
                    - { type: 'group', columns: 4, icon: 'bullhorn', label: 'CFP' }
                    - { property: 'cfpUrl', type: 'url' }
                    - { property: 'cfpEndAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { type: 'group', columns: 4, icon: 'cubes', label: 'Metadata' }
                    - { property: 'articleUrl', type: 'url' }
            show:
                fields:
                    <<: *conferenceShowFields
        ExcludedConference:
            class: App\Entity\Conference
            controller: App\Controller\Admin\ConferenceController
            disabled_actions: ['delete', 'new']
            list:
                title: 'Excluded Conferences'
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'includeConference', label: 'Re-include', icon: 'arrow-left' }
                sort: ['endAt', 'DESC']
                dql_filter: 'entity.excluded = true'
                fields:
                    <<: *conferenceListFields
            show:
                fields:
                    <<: *conferenceShowFields
            form:
                fields:
                    <<: *conferencesEditFields
