easy_admin:
    entities:
        PassedConference:
            class: App\Entity\Conference
            list:
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'excludeConference', label: 'Exclude', icon: 'times' }
                sort: ['endAt', 'DESC']
                dql_filter: 'entity.endAt < CURRENT_DATE() AND entity.excluded = false'
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'startAt', type: 'date' }
                    - { property: 'endAt', type: 'date' }
                    - { property: 'source', type: 'text' }
                    - { property: 'tags', type: 'array' }
        NextConference:
            class: App\Entity\Conference
            disabled_actions: ['show']
            list:
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'excludeConference', label: 'Exclude', icon: 'times' }
                sort: ['startAt', 'ASC']
                dql_filter: 'entity.endAt >= CURRENT_DATE() AND entity.excluded = false'
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'city', type: 'text' }
                    - { property: 'country', type: 'country'}
                    - { property: 'startAt', type: 'date' }
                    - { property: 'cfpUrl', type: 'url', template: 'easy_admin/Conference/cfpUrl.html.twig' }
                    - { property: 'cfpEndAt', type: 'date' }
                    - { property: 'source', type: 'text' }
                    - { property: 'tags', type: 'array' }
            form:
                fields:
                    - { type: 'group', columns: 4, icon: 'pencil', label: 'Conference' }
                    - { property: 'name', type: 'text' }
                    - { property: 'city', type: 'text' }
                    - { property: 'country', type: 'country' }
                    - { property: 'startAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'endAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { property: 'siteUrl', type: 'url' }
                    - { type: 'group', columns: 4, icon: 'bullhorn', label: 'CFP' }
                    - { property: 'cfpUrl', type: 'url' }
                    - { property: 'cfpEndAt', type: 'date', 'type_options': { 'widget': 'single_text' } }
                    - { type: 'group', columns: 4, icon: 'cubes', label: 'Metadata' }
                    - { property: 'tags' }
                    - { property: 'articleUrl', type: 'url' }
        ExcludedConferences:
            class: App\Entity\Conference
            list:
                filters: ['name', 'city', 'country', 'startAt', 'tags', 'source']
                actions:
                    - { name: 'includeConference', label: 'Re-include', icon: 'arrow-left' }
                sort: ['endAt', 'DESC']
                dql_filter: 'entity.excluded = true'
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'startAt', type: 'date' }
                    - { property: 'cfpUrl', type: 'url', template: 'easy_admin/Conference/cfpUrl.html.twig' }
                    - { property: 'cfpEndAt', type: 'date' }
                    - { property: 'source', type: 'text' }
                    - { property: 'tags', type: 'array' }
