easy_admin:
    entities:
        Submit:
            class: App\Entity\Submit
            disabled_actions: ['show']
            edit:
                role: SUBMIT_EDIT
            delete:
                role: SUBMIT_EDIT
            list:
                filters: ['talk', 'conference', 'submittedAt', 'status', 'users']
                role: ROLE_USER
                fields:
                    - { property: 'talk' }
                    - { property: 'conference' }
                    - { property: 'submittedAt', type: 'date' }
                    - { property: 'status', template: 'easy_admin/Submit/status.html.twig' }
                    - { property: 'users', type: 'array', label: 'Speakers' }
            form:
                item_permission: SUBMIT_EDIT
                fields:
                    - { type: 'group', columns: 6, icon: 'pencil', label: 'Submit' }
                    -   property: 'talk'
                        type: entity
                        type_options:
                            class: App\Entity\Talk
                    -   property: 'conference'
                        type: easyadmin_autocomplete
                        type_options:
                            class: App\Entity\Conference
                    - { property: 'submittedAt', 'type_options': { 'widget': 'single_text' } }
                    - { type: 'group', columns: 6, icon: 'cubes', label: 'Metadata' }
                    -   property: 'status'
                        type: 'choice'
                        type_options:
                            choices: !php/const App\Entity\Submit::STATUSES
                            expanded: true
                            label_attr:
                                class: 'radio-inline'
                    -   property: 'users'
                        type: easyadmin_autocomplete
                        type_options:
                            multiple: true
                            class: App\Entity\User
