easy_admin:
    entities:
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'conferences' }
                    - { property: 'selected'}
            form:
                fields:
                    - { type: 'group', columns: 6, icon: 'pencil', label: 'Tag' }
                    - { property: 'name', type: 'text' }
