easy_admin:
    entities:
        Talk:
            class: App\Entity\Talk
            list:
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'submits' }
            show:
                fields:
                    - { property: 'title' }
                    - { property: 'intro' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
                    - { property: submits, label: 'Submits', type: embedded_list, type_options: { entity: Submit, filters: { 'entity.talk': 'form:parent.data.id' } } }
            new:
                fields: &talkFields
                    1: { type: 'group', columns: 6, icon: 'pencil', label: 'Talk' }
                    2: { property: 'title', type: 'text' }
                    3: { property: 'intro', type: 'textarea' }
                    4: { type: 'group', columns: 6, icon: 'send', label: 'Publication' }
                    5: { property: 'conference', type: 'easyadmin_autocomplete', type_options: { mapped: false, class: App\Entity\Conference } }
            edit:
                fields:
                    <<: *talkFields
                    4: { type: 'group', columns: 6, icon: 'send', label: 'Submits' }
                    5: { property: submits, type: collection, type_options: { entry_type: App\Form\TalkSubmitType } }
