easy_admin:
    entities:
        Talk:
            controller: App\Controller\Admin\TalkController
            class: App\Entity\Talk
            list:
                filters: ['title', 'intro', 'createdAt']
                item_permission: ['ROLE_TALK_SHOW']
                fields:
                    - { property: 'title', type: 'text' }
                    - { property: 'submits' }
                    - { property: 'createdAt', type: 'date' }
                    - { property: 'authors', template: 'easy_admin/Talk/authors.html.twig', css_class: 'w-25' }
            show:
                fields:
                    - { property: 'title' }
                    - { property: 'intro' }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }
                    - { property: submits, label: 'Submissions', type: embedded_list, type_options: { entity: Submit, filters: { 'entity.talk': 'form:parent.data.id' } } }

            edit:
                fields: &talkFields
                    1: { type: 'group', columns: 6, icon: 'pencil', label: 'Talk' }
                    2: { property: 'title', type: 'text' }
                    3: { property: 'intro', type: 'textarea' }
                    4: { type: 'group', columns: 6, icon: 'send', label: 'Submits' }
                    5: { property: submits, type: collection, type_options: { entry_type: App\Form\EasyAdmin\TalkSubmitType } }

            new:
                fields:
                    <<: *talkFields
                    4: { type: 'group', columns: 6, icon: 'send', label: 'Publication' }
                    5: { property: 'conference', type: 'App\Form\EasyAdmin\FutureConferencesType', type_options: { mapped: false, class: App\Entity\Conference, multiple: true, attr: { data-widget: 'select2' } } }
                    6: { property: authors, type: App\Form\EasyAdmin\TalkUserType, type_options: { mapped: false, required: true } }

