easy_admin:
    entities:
        Talk:
            class: App\Entity\Talk
            list:
                fields:
                    - { property: 'id', type: 'text' }
                    - { property: 'title', type: 'text' }
                    - { property: 'submits' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', icon: 'pencil', label: 'Talk' }
                    - { property: 'title', type: 'text' }
                    - { property: 'intro', type: 'textarea' }
