easy_admin:
    entities:
        User:
            class: App\Entity\User
            disabled_actions: ['show', 'delete']
            list:
                item_permission: ['ROLE_ADMIN']
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'submits' }
            form:
                item_permission: ['ROLE_ADMIN']
                fields:
                    - { type: 'group', columns: 6, icon: 'pencil', label: 'User' }
                    - { property: 'name', type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'job', type: 'text' }
                    - { property: 'twitterAccount', type: 'text' }
                    - { property: 'tshirtSize', type: 'choice', type_options: { choices: { XS: 'XS', S: 'S', M: 'M', L: 'L', XL: 'XL', XXL: 'XXL', XXXL: 'XXXL' } } }
                    - { property: 'bio', type: 'textarea' }
                    - { property: 'foodPreferences', type: 'textarea' }
                    - { property: 'allergies', type: 'textarea' }
                    - { type: 'group', columns: 6, icon: 'lock', label: 'Roles' }
                    -   property: roles
                        role: ROLE_ADMIN
                        type: choice
                        type_options:
                            expanded: true
                            multiple: true
                            choices:
                                Admin: ROLE_ADMIN
                                User: ROLE_USER
