name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    SSH_AUTH_SOCK: '/ssh-agent'

jobs:
    ci:
        name: Check Coding Standards
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: mbstring, fileinfo, json, intl, dom
                    tools: castor

            -   name: Build and start the infrastructure
                run: castor start

            -   name: Install quality tools
                run: castor qa:install

            -   name: Check coding standards
                run: castor qa:cs --dry-run

            -   name: Lint Twig files
                run: castor qa:twig-lint

            -   name: Lint YAML files
                run: castor qa:yaml-lint

            -   name: Run PHPStan
                run: castor qa:phpstan

            -   name: Load fixtures
                run: castor app:db:fixtures

            -   name: Run the tests
                run: castor tests
